# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'draft.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import subprocess
import time
from PyQt5 import QtCore, QtGui, QtWidgets#, QWebEngineView
from PyQt5.QtWidgets import QLabel
from PyQt5.QtGui import QPixmap, QColor
from PyQt5.QtCore import QSize
import asyncio, asyncvnc
from PIL import Image


async def vnc_capture(port=5900):
    try:
        async with asyncvnc.connect('localhost', port) as client:
            pixels = await client.screenshot()
            image = Image.fromarray(pixels)
            image.save('shot.png')
    except:
        try:
            os.remove('shot.png')
        except:
            return


class Ui_MainWindow(object):

    vnc_num = 1
    vm_buttons = []
    curr_vm = ""

    def setupUi(self, MainWindow):
        vm_list = self.get_vm_list()
        self.curr_vm = vm_list[0]

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setObjectName("MainWindow")
        MainWindow.showFullScreen();
        MainWindow.setMinimumSize(QtCore.QSize(1645, 883))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1620, 960, 251, 61))
        self.pushButton.setStyleSheet("font: 14pt \"Noto Sans\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.open_vm(MainWindow))
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 351, 1041))
        self.frame.setMinimumSize(QtCore.QSize(351, 831))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        for i, vm in enumerate(vm_list):
            button = QtWidgets.QPushButton(self.frame)
            button.name = vm
            button.setGeometry(QtCore.QRect(10, 20 + 60 * i, 300, 50))
            button.setStyleSheet("font: 14pt \"Noto Sans\";")
            button.setObjectName("vmButton_" + str(i))
            button.setText(_translate("MainWindow", vm))
            button.clicked.connect(lambda args, name=vm: self.set_vnc(name))
            self.vm_buttons.append(button)

        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame)
        self.verticalScrollBar.setGeometry(QtCore.QRect(330, 10, 16, 1021))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")

        #self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        #self.openGLWidget = QtWebEngineWidgets(self.centralwidget)
        #self.openGLWidget.setGeometry(QtCore.QRect(400, 130, 1471, 791))
        #self.openGLWidget.setObjectName("openGLWidget")
        #self.openGLWidget.setUrl(QtCore.QUrl("tcp://192.168.88.248:5977"))

        self.preview = QtWidgets.QLabel(self.centralwidget)
        pixmap = QtGui.QPixmap("shot.png")
        self.preview.setPixmap(pixmap)
        self.preview.setGeometry(QtCore.QRect(500, 130, 1270, 790))
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 20, 231, 51))
        self.label.setStyleSheet("font: 24pt \"Noto Sans\";")
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1921, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Enter VM"))
        self.label.setText(_translate("MainWindow", self.curr_vm))

    def open_vm(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        if self.curr_vm == "Host":
            MainWindow.close()
        else:
            try:
                output = subprocess.check_output(f"vm start {self.curr_vm}", shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
                self.pushButton.setText("Starting...")
                #self.pushButton.setText(_translate("MainWindow", "Starting.."))
                if "running already" not in output:
                    time.sleep(1)
                cmd1 = f"vm info {self.curr_vm} | grep vnc | cut -d':' -f3"
                port = subprocess.check_output(cmd1, shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
                vnc = int(port) - 5900
                cmd2 = f"vncviewer -Fullscreen localhost:{vnc}"
                output = subprocess.check_output(cmd2, shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
                self.pushButton.setText("Enter VM")
                #self.pushButton.setText(_translate("MainWindow", "Enter VM"))
                #print("Command output:\n", output)
            except subprocess.CalledProcessError as e:
                print("Error occurred:\n", e.output)

    def set_vnc(self, name):
        _translate = QtCore.QCoreApplication.translate
        #self.vnc_num = num
        self.curr_vm = name
        self.label.setText(_translate("MainWindow", name))
        if name == "Host":
            pixmap = QPixmap(QSize(1270, 790))
            pixmap.fill(QColor("black"))
            self.preview.setPixmap(pixmap)
            self.preview.setGeometry(QtCore.QRect(500, 130, 1270, 790))
            try:
                os.remove("shot.png")
            except:
                return
            return
        cmd1 = f"vm info {name} | grep vnc | cut -d':' -f3"
        port = subprocess.check_output(cmd1, shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
        if len(port) == 0:
            pixmap = QPixmap(QSize(1270, 790))
            pixmap.fill(QColor("black"))
            self.preview.setPixmap(pixmap)
            self.preview.setGeometry(QtCore.QRect(500, 130, 1270, 790))
            try:
                os.remove("shot.png")
            except:
                return
            return
        asyncio.run(vnc_capture(int(port)))
        if os.path.isfile("shot.png"):
            pixmap = QtGui.QPixmap("shot.png")
            self.preview.setPixmap(pixmap)

    def get_vm_list(self):
        output = subprocess.check_output("vm list | grep -v CPU | awk '{ print $1 }'", shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
        vm_list = self.parse_vm_settings(output)
        vm_list.append('Host')
        return vm_list

    def parse_vm_settings(self, settings_str):
        result = []
    
        for line in settings_str.strip().splitlines():
            if not line.strip():
                continue
            vm_name = line.strip()
            result.append(vm_name)
    
        return result
