# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'draft.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import subprocess
import time
from PyQt5 import QtCore, QtGui, QtWidgets#, QWebEngineView
from PyQt5.QtWidgets import QLabel
from PyQt5.QtGui import QPixmap, QColor
from PyQt5.QtCore import QSize
import asyncio, asyncvnc
from PIL import Image
import libzfs_core as lzc
from datetime import datetime


vncviewer_path="./vncviewer"
vm_dir_dataset="zroot/vm"


async def vnc_capture(port=5900):
    try:
        async with asyncvnc.connect('localhost', port) as client:
            pixels = await client.screenshot()
            image = Image.fromarray(pixels)
            image.save('shot.png')
    except:
        try:
            os.remove('shot.png')
        except:
            return


class Ui_MainWindow(object):

    vnc_num = 1
    vm_buttons = []
    curr_vm = ""

    def setupUi(self, MainWindow):
        vm_list = self.get_vm_list()
        self.curr_vm = vm_list[0]

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setObjectName("MainWindow")
        MainWindow.showFullScreen();
        MainWindow.setMinimumSize(QtCore.QSize(1645, 883))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1620, 960, 251, 61))
        self.pushButton.setStyleSheet("font: 14pt \"Noto Sans\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.open_vm(MainWindow))

        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setGeometry(QtCore.QRect(1320, 960, 251, 61))
        self.exportButton.setStyleSheet("font: 14pt \"Noto Sans\";")
        self.exportButton.setObjectName("exportButton")
        self.exportButton.clicked.connect(lambda: self.export_vm(vm=self.curr_vm))

        self.importButton = QtWidgets.QPushButton(self.centralwidget)
        self.importButton.setGeometry(QtCore.QRect(1020, 960, 251, 61))
        self.importButton.setStyleSheet("font: 14pt \"Noto Sans\";")
        self.importButton.setObjectName("importButton")
        self.importButton.clicked.connect(lambda: self.import_vm())

        self.exportDiffButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportDiffButton.setGeometry(QtCore.QRect(720, 960, 251, 61))
        self.exportDiffButton.setStyleSheet("font: 14pt \"Noto Sans\";")
        self.exportDiffButton.setObjectName("exportDiffButton")
        self.exportDiffButton.clicked.connect(lambda: self.export_diff())

        self.importDiffButton = QtWidgets.QPushButton(self.centralwidget)
        self.importDiffButton.setGeometry(QtCore.QRect(420, 960, 251, 61))
        self.importDiffButton.setStyleSheet("font: 14pt \"Noto Sans\";")
        self.importDiffButton.setObjectName("importDiffButton")
        self.importDiffButton.clicked.connect(lambda: self.import_diff())
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 351, 1041))
        self.frame.setMinimumSize(QtCore.QSize(351, 831))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        for i, vm in enumerate(vm_list):
            button = QtWidgets.QPushButton(self.frame)
            button.name = vm
            button.setGeometry(QtCore.QRect(10, 20 + 60 * i, 300, 50))
            button.setStyleSheet("font: 14pt \"Noto Sans\";")
            button.setObjectName("vmButton_" + str(i))
            button.setText(_translate("MainWindow", vm))
            button.clicked.connect(lambda args, name=vm: self.set_vnc(name))
            self.vm_buttons.append(button)

        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame)
        self.verticalScrollBar.setGeometry(QtCore.QRect(330, 10, 16, 1021))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")

        #self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        #self.openGLWidget = QtWebEngineWidgets(self.centralwidget)
        #self.openGLWidget.setGeometry(QtCore.QRect(400, 130, 1471, 791))
        #self.openGLWidget.setObjectName("openGLWidget")
        #self.openGLWidget.setUrl(QtCore.QUrl("tcp://192.168.88.248:5977"))

        self.preview = QtWidgets.QLabel(self.centralwidget)
        pixmap = QtGui.QPixmap("shot.png")
        self.preview.setPixmap(pixmap)
        self.preview.setGeometry(QtCore.QRect(500, 130, 1270, 790))
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 20, 231, 51))
        self.label.setStyleSheet("font: 24pt \"Noto Sans\";")
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1921, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Enter VM"))
        self.exportButton.setText(_translate("MainWindow", "Export VM"))
        self.importButton.setText(_translate("MainWindow", "Import VM"))
        self.exportDiffButton.setText(_translate("MainWindow", "Export Diff"))
        self.importDiffButton.setText(_translate("MainWindow", "Import Diff"))
        self.label.setText(_translate("MainWindow", self.curr_vm))

    def open_vm(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        if self.curr_vm == "Host":
            MainWindow.close()
        else:
            try:
                output = subprocess.check_output(f"mdo vm start {self.curr_vm}", shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
                self.pushButton.setText("Starting...")
                #self.pushButton.setText(_translate("MainWindow", "Starting.."))
                if "running already" not in output:
                    time.sleep(1)
                cmd1 = f"mdo vm info {self.curr_vm} | grep vnc | cut -d':' -f3"
                port = subprocess.check_output(cmd1, shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
                vnc = int(port) - 5900
                cmd2 = f"{vncviewer_path} -Fullscreen localhost:{vnc}"
                output = subprocess.check_output(cmd2, shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
                self.pushButton.setText("Enter VM")
                #self.pushButton.setText(_translate("MainWindow", "Enter VM"))
                #print("Command output:\n", output)
            except subprocess.CalledProcessError as e:
                print("Error occurred:\n", e.output)

    def set_vnc(self, name):
        _translate = QtCore.QCoreApplication.translate
        #self.vnc_num = num
        self.curr_vm = name
        self.label.setText(_translate("MainWindow", name))
        if name == "Host":
            pixmap = QPixmap(QSize(1270, 790))
            pixmap.fill(QColor("black"))
            self.preview.setPixmap(pixmap)
            self.preview.setGeometry(QtCore.QRect(500, 130, 1270, 790))
            try:
                os.remove("shot.png")
            except:
                return
            return
        cmd1 = f"mdo vm info {name} | grep vnc | cut -d':' -f3"
        port = subprocess.check_output(cmd1, shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
        if len(port) == 0:
            pixmap = QPixmap(QSize(1270, 790))
            pixmap.fill(QColor("black"))
            self.preview.setPixmap(pixmap)
            self.preview.setGeometry(QtCore.QRect(500, 130, 1270, 790))
            try:
                os.remove("shot.png")
            except:
                return
            return
        asyncio.run(vnc_capture(int(port)))
        if os.path.isfile("shot.png"):
            pixmap = QtGui.QPixmap("shot.png")
            self.preview.setPixmap(pixmap)

    def get_vm_list(self):
        output = subprocess.check_output("mdo vm list | grep -v CPU | awk '{ print $1 }'", shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
        vm_list = self.parse_vm_settings(output)
        vm_list.append('Host')
        return vm_list

    def parse_vm_settings(self, settings_str):
        result = []
    
        for line in settings_str.strip().splitlines():
            if not line.strip():
                continue
            vm_name = line.strip()
            result.append(vm_name)
    
        return result

    def export_vm(self, vm="ubuntu0", export_dir="/tmp"):
        vm_dataset=f"{vm_dir_dataset}/{vm}"
        vm_base_snap=f"{vm_dataset}@snap0"
        if not lzc.lzc_exists(vm_base_snap.encode()):
            print(f"{vm_base_snap} not exist, snapshoting")
            try:
                lzc.lzc_snapshot([vm_base_snap.encode()])
            except Exception as err:
                print(err)
                return
 
        with open(f"{export_dir}/{vm}-base.zfs", 'w') as f:
            print(f"exporting {vm_base_snap}")
            lzc.lzc_send(vm_base_snap.encode(), fromsnap=None, fd=f.fileno())

        return

    def import_vm(self, vm="ubuntu3", img="/tmp/ubuntu0-base.zfs"):
        vm_dataset=f"{vm_dir_dataset}/{vm}"
        vm_base_snap=f"{vm_dataset}@snap0"

        if lzc.lzc_exists(vm_dataset.encode()):
            print(f"{vm_dataset} exists, cannot import")
            return

        if not os.path.isfile(img):
            print(f"{img} is not a file")
            return

        with open(img, 'r') as f:
            print(f"Importing {vm_base_snap}")
            print(f.fileno())
            #lzc.lzc_receive(vm_base_snap.encode(), fd=f.fileno())
            subprocess.run(f"cat {img} | mdo zfs recv {vm_dataset}", shell=True)

    def export_diff(self, vm="ubuntu2", export_dir="/tmp"):
        timestamp_str = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
        vm_dataset=f"{vm_dir_dataset}/{vm}"
        vm_base_snap=f"{vm_dataset}@snap0"
        vm_new_snap=f"{vm_dataset}@{timestamp_str}"

        if not lzc.lzc_exists(vm_base_snap.encode()):
            print(f"{vm_base_snap} not exist, cannot export diff")
            return

        lzc.lzc_snapshot([vm_new_snap.encode()])

        diff_img = f"{export_dir}/{vm}-{timestamp_str}.zfs"
        with open(diff_img, 'w') as f:
            print(f"Exporting diff {vm_new_snap} to {diff_img}")
            lzc.lzc_send(vm_new_snap.encode(), fromsnap=vm_base_snap.encode(), fd=f.fileno())
        #subprocess.run(f"zfs send -i {vm_base_snap} {vm_new_snap} > {diff_img}", shell=True)

    def import_diff(self, vm="ubuntu3", img="/tmp/ubuntu2-diff.zfs"):
        #timestamp_str = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
        vm_dataset=f"{vm_dir_dataset}/{vm}"
        vm_base_snap=f"{vm_dataset}@snap0"
        #vm_new_snap=f"{vm_dataset}@{timestamp_str}"

        if not lzc.lzc_exists(vm_base_snap.encode()):
            print(f"{vm_base_snap} not exist, cannot export diff")
            return

        if not os.path.isfile(img):
            print(f"{img} is not a file")
            return

        with open(img, 'r') as f:
            print(f"Importing diff {img} to {vm_dataset}")
            #lzc.lzc_receive(vm_new_snap.encode(), fd=f.fileno())
            subprocess.run(f"cat {img} | mdo zfs receive {vm_dataset}", shell=True)

        conf = subprocess.check_output(f"ls /{vm_dataset} | grep .conf", shell=True, stderr=subprocess.STDOUT, universal_newlines=True).strip()
        os.rename(f"/{vm_dataset}/{conf}", f"/{vm_dataset}/{vm}.conf")
