loader="uefi"
cpu=2
memory=1G
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0"
disk0_dev="sparse-zvol"
uuid="7d9b99b3-baa9-4e50-9aef-0e1115059247"
network0_mac="58:9c:fc:02:e9:87"
graphics="yes"
graphics_res="1920x1080"
